### ISSUE TITLE
Add dynamic rendering of case diagrams

### ISSUE THREAD

**Issue by larsduelfer** [camunda-community-hub/camunda-acm-plugin#36]
Currently, the plugin shows a static image as the diagram of the deployed cases. It would be great to have the same functionality for cases  than are already available for processes and have a rendering enginge that dynamically creates case diagrams.

Furthermore, the dynamic view of one case instance could be enhanced with tokens on the case diagram showing the current state of the execution (like the process plugin allows).

**Comment by rpeinl** [comment]
I just stumbled upon the same problem. We are deploying cases and processes using only the XML file. For processes, cockpit still shows the diagram, since it seems to build on bpmn.js, whereas the Case plugin tries to load the diagram as an image from the server, which is not working in our case since there is no diagram on the server.
